version: "3.7"
services:
  client:
    environment:
      - NODE_ENV=production
      - PORT=5081
      - DATABASE_URL=file:../db/data.sqlite
    image: solonsscale/oceanus-prm
    working_dir: /app
    stdin_open: true
    ports:
      - "5081:5081"
    restart: unless-stopped
    volumes:
      - prm_data:/app

volumes:
  prm_data: